services:
  backend:
    build: ./backend
    volumes:
      - ./backend/instance:/app/instance
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
